---
title: "DSAN-5000: Introduction"
---

See the following link for more information about the author: [about me](../../index.html)

# iPhone's Popularity In the Market

## Topics Introduction
* `summary`
  
   Over the decades, Apple's products are always the most popular products in the markets. However, with more and more new products introduced to the market. Is Apple products, especially iphone, are still popular in the market?
* `Importance`
  
   The iPhone has significantly influenced technology and culture since its introduction in 2007. It has influenced and impacted a genration, thus everyone curious about how apple performed in the recent years. Its role in shaping consumer behaviors, communication norms, and mobile technology makes it a rich subject for study.
* `Why the reader should continue`

   The choices and preferences of iPhone users can reflect broader trends in consumer behavior. Consumers can pick better products through this research topic and see how consumers react to Apple's products.
* `what work had done`
  
   The researchers had done many data collection, data preprocessing, and set up machine learning models to do the logistic regression, decision trees and random forest, etc. They also had done so many behavioral analysis to analyze the popularity trend for electronic products.
* `what are the “different points of views”/interpretations in the literature`
  
  Some literature emphasizes Apple's commitment to innovation and high-quality products as a key factor in its popularity. This view holds that the company's focus on design, user experience, and robust performance drives consumer preference. Some authors also discuss Apple's cultural impact, suggesting that its products have become more than just technology but a part of modern culture. 
* `what exploring`: 
  
  1. We can explore how people evaluate an electronic products as a good products.
  2. We can explore the stock market for the Apple Products and how it stock prices changes
  3. We can collect customers' review/news on Apple products, to see how everyone like apple's products.
* `goals and hypothesis`
  
   The purpose of this study is to determine whether Apple products are still in demand and to ascertain how the general public feels about the company's latest offerings. In addition, I'd like to know what specifications a mobile phone should have in order to draw in customers. So that when the next generation of iPhones came out, I could use this model to predict its popularity, I should train some models that can predict a product's popularity based on its functions.

## 2. 10 questions to address
* Can customer reviews and sentiment analysis on social media predict the market success of a new Apple product release?
* How can we predict whether Apple's products would be popular in the future?
* How does Apple's stock performed?
* What kind of electronic products can be seem as a good product to buy?
* What kind of models we can used to predict people's attitude with reviews?
* Can we use machine learning to identify key factors that predict an Apple product's popularity based on historical data?
* How does the pricing of Apple products compare with competitors over time, and what is the impact on market share and consumer choice?
* What are the trends in iPhone sales over the last decade, and how do they correlate with product release cycles and feature enhancements?
* Can decision tree analysis help in identifying the most significant factors that lead to a successful Apple Store location?
* How can we eliminate the unnecessary feature for predicting the Apple's products



## 3. Realated Articles
### A comparative study of online consumer reviews of Apple iPhone across Amazon, Twitter and MouthShut platforms[^1] 
[^1]: Kundu, Supratim, and Swapnajit Chakraborti. “A Comparative Study of Online Consumer Reviews of Apple IPhone across Amazon, Twitter and MouthShut Platforms.” Electronic Commerce Research, vol. 22, no. 3, 2022, pp. 925–50, https://doi.org/10.1007/s10660-020-09429-w.

`Abstract`

* The purpose of the paper is to understand if the online consumer reviews differ across the review platforms over the internet. We aim to find the features of the reviews from various platforms and ultimately create a typology of the reviews for those platforms. We apply mixed methods including both quantitative and qualitative techniques to arrive at the conclusion. We find consumers share their views on the highest number of topics in the ecommerce website. Consumers share in-depth views, but on a limited number of topics in other dedicated review platforms. Social media falls somewhere in the middle among these two platforms. While looking into the contents, we could generate themes and meta-themes from these reviews. Based on these facts, we create a typology/ontology for reviews from these platforms and map the motives of reviewers from each platform into the meta-themes identified. Managers can use our findings to boost their online review strategy according to the platform of their interest.

### The influence of brand popularity, perceived quality, price, and need on purchase intention iPhone products in Purwokerto[^2]
[^2]: Rizaldi, Herna. " The influence of brand popularity, perceived quality, price, and need on purchase intention iPhone products in Purwokerto." Jurnal Akuntansi, Manajemen dan Ekonomi [Online], 24.2 (2022): 14-22. Web. 7 Nov. 2023

`Abstract`

* This study is a survey research that aims to determine and analyze the effect of brand popularity, perceived quality, price, and need on purchase intentions on iPhone products at Purwokerto city. The sample size in this study amounted to 120 using purposive sampling technique. Based on the results of data processing, it is known that brand popularity has no significant and negative effect on purchase intention. Price has a significant and negative effect on purchase intention. Perceived quality and need have a significant and positive effect on purchase intention. The findings in this study are that popularity is not always a consumer factor in generating purchase intentions, while the factor that has the greatest influence on purchase intentions is need.

## Next Steps:
To complete this research topic, I need to find datasets and related information related to people's reviews that reflect people's actual reaction related to Apple brands and iPhone Products. Also, I need to find some datasets that can help me to research what kind of quality of functions that would attract a customer to purchase. Whether Apple products perform well in those functions area?

After I collected the datasets, I need to clean them as needed and prepare for the future model use and data analysis process.